#!/usr/bin/env python3
"""
Builds assets/js/search-index.js — a static, client-side search index for
the site's nav search bar.

Excludes every hub `index.html` page (site root + each realm/section hub)
and includes every other .html page: tricks, drills, and essentials pages.
"""
import json
import re
from pathlib import Path
from bs4 import BeautifulSoup

ROOT = Path(__file__).parent
SITE_SUFFIX_RE = re.compile(r"\s*—\s*The Snowboard Compendium\s*$")

EXCLUDE_DIRS = {".git"}


def find_pages():
    pages = []
    for path in sorted(ROOT.rglob("*.html")):
        if any(part in EXCLUDE_DIRS for part in path.parts):
            continue
        if path.name == "index.html":
            continue  # hub / listing pages are excluded from the search index
        pages.append(path)
    return pages


def extract_entry(path: Path):
    html = path.read_text(encoding="utf-8")
    soup = BeautifulSoup(html, "html.parser")

    title_tag = soup.find("title")
    title = SITE_SUFFIX_RE.sub("", title_tag.get_text(strip=True)) if title_tag else path.stem

    desc_tag = soup.find("meta", attrs={"name": "description"})
    description = desc_tag["content"].strip() if desc_tag and desc_tag.get("content") else ""

    crumb_items = soup.select(".breadcrumb__item")
    crumb_texts = [c.get_text(strip=True) for c in crumb_items]
    # Drop the leading "Home" crumb and the trailing current-page crumb
    # (that's just the title again) to get the category path.
    if crumb_texts and crumb_texts[0] == "Home":
        crumb_texts = crumb_texts[1:]
    if crumb_texts and crumb_texts[-1] == title:
        crumb_texts = crumb_texts[:-1]
    breadcrumb = " › ".join(crumb_texts)

    difficulty = None
    badge = soup.select_one(".meta-rail__badge .badge[data-difficulty]")
    if badge:
        difficulty = badge.get("data-difficulty")

    realm = None
    category = None
    for row in soup.select(".meta-row"):
        label = row.select_one(".meta-row__label")
        value = row.select_one(".meta-row__value")
        if not label or not value:
            continue
        label_text = label.get_text(strip=True).lower()
        if label_text == "realm":
            realm = value.get_text(strip=True)
        elif label_text == "category":
            category = value.get_text(strip=True)

    url = path.relative_to(ROOT).as_posix()

    return {
        "title": title,
        "url": url,
        "breadcrumb": breadcrumb,
        "description": description,
        "difficulty": difficulty,
        "realm": realm,
        "category": category,
    }


def main():
    pages = find_pages()
    entries = [extract_entry(p) for p in pages]
    entries.sort(key=lambda e: e["title"].lower())

    out_path = ROOT / "assets" / "js" / "search-index.js"
    js = "// Auto-generated by build_search_index.py — do not hand-edit.\n"
    js += "window.SITE_SEARCH_INDEX = " + json.dumps(entries, ensure_ascii=False, indent=None) + ";\n"
    out_path.write_text(js, encoding="utf-8")
    print(f"Wrote {len(entries)} entries to {out_path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
